class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道', theme:['グルメ','リゾート','その他' ], info:'海鮮が美味しい', image:'#'},
    { id: 2, name: '青森県', theme:['その他'], info:'海鮮が美味しい', image:'#'},
    { id: 3, name: '岩手県', theme:['その他'], info:'海鮮が美味しい', image:'#'},
    { id: 4, name: '宮城県', theme:['グルメ', 'その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 5, name: '秋田県', theme:['グルメ', '温泉', 'その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 6, name: '山形県', theme:['温泉', 'その他'], info:'海鮮が美味しい', image:'#'},
    {id: 7, name: '福島県',theme:['温泉', 'その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 8, name: '茨城県', theme:['その他'], info:'海鮮が美味しい', image:'#'},
    {id: 9, name: '栃木県', theme:['温泉','その他' ], info:'海鮮が美味しい', image:'#'},
    {id: 10, name: '群馬県', theme:['温泉','その他' ], info:'海鮮が美味しい', image:'#'},
    {id: 11, name: '埼玉県', theme:['その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 12, name: '千葉県', theme:['リゾート','テーマパーク','その他' ], info:'海鮮が美味しい', image:'#'},
    {id: 13, name: '東京都',theme:['グルメ','テーマパーク','その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 14, name: '神奈川県', theme:['リゾート','テーマパーク','その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 15, name: '新潟県', theme:['グルメ','その他' ], info:'海鮮が美味しい', image:'#'},
    {id: 16, name: '富山県', theme:['グルメ','その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 17, name: '石川県', theme:['グルメ','その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 18, name: '福井県', theme:['その他' ], info:'海鮮が美味しい', image:'#'},
    {id: 19, name: '山梨県', theme:['テーマパーク','その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 20, name: '長野県', theme:['リゾート','その他' ], info:'海鮮が美味しい', image:'#'}, 
    {id: 21, name: '岐阜県', theme:['温泉','その他' ], info:'海鮮が美味しい', image:'#'},
    {id: 22, name: '静岡県', theme:['グルメ', 'リゾート','その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 23, name: '愛知県', theme:['グルメ','その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 24, name: '三重県', theme:['リゾート','テーマパーク', 'その他'], info:'海鮮が美味しい', image:'#'},
    {id: 25, name: '滋賀県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 26, name: '京都府', theme:['グルメ','その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 27, name: '大阪府', theme:['グルメ','テーマパーク','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 28, name: '兵庫県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 29, name: '奈良県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 30, name: '和歌山県', theme:['リゾート','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 31, name: '鳥取県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 32, name: '島根県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 33, name: '岡山県', theme:['その他'], info:'海鮮が美味しい', image:'#'},
    {id: 34, name: '広島県', theme:['グルメ','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 35, name: '山口県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 36, name: '徳島県', theme:['その他'], info:'海鮮が美味しい', image:'#'},
    {id: 37, name: '香川県', theme:['グルメ','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 38, name: '愛媛県', theme:['その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 39, name: '高知県', theme:['その他'], info:'海鮮が美味しい', image:'#'},
    {id: 40, name: '福岡県', theme:['グルメ','その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 41, name: '佐賀県', theme:['温泉', 'その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 42, name: '長崎県', theme:['テーマパーク','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 43, name: '熊本県', theme:['グルメ', '温泉','その他'], info:'海鮮が美味しい', image:'#'}, 
    {id: 44, name: '大分県', theme:['温泉','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 45, name: '宮崎県', theme:['リゾート','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 46, name: '鹿児島県', theme:['グルメ','その他'], info:'海鮮が美味しい', image:'#'},
    {id: 47, name: '沖縄県', theme:['リゾート','その他'], info:'海鮮が美味しい', image:'#'},
  ]

  include ActiveHash::Associations
  has_many :destinations
  
  end